# Generated by Django 3.1.5 on 2021-02-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ismi')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': 'Aloqalar',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kurs nomi')),
                ('time', models.CharField(max_length=50, verbose_name='Kurs vaqti')),
                ('image', models.ImageField(upload_to='course_images/')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Narxi')),
                ('student_age', models.CharField(max_length=50, verbose_name='Talabalar yosh chegarasi')),
                ('size', models.CharField(max_length=50, verbose_name='Talabalar soni')),
                ('teacher', models.CharField(max_length=150, verbose_name='Ustoz')),
                ('duration', models.CharField(blank=True, max_length=50, verbose_name='Davom etish vaqti')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
    ]
