# Generated by Django 3.1.5 on 2021-02-08 10:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default=datetime.datetime(2021, 2, 8, 10, 8, 2, 848758, tzinfo=utc), verbose_name='Matni'),
            preserve_default=False,
        ),
    ]
