# Generated by Django 3.1.5 on 2021-02-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210217_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ism-Familya')),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=50, verbose_name='Tanlagan kursi')),
                ('message', models.TextField(verbose_name="Qo'shimcha xabar")),
            ],
            options={
                'verbose_name': "A'zo bo'lish",
                'verbose_name_plural': "A'zo bo'lganlar",
            },
        ),
    ]
