# Generated by Django 3.1.5 on 2021-02-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='course',
            field=models.CharField(choices=[('Python', 'python'), ('Javascript', 'javascript'), ('C++', 'cpp'), ('C#', 'csharp'), ('Ruby', 'ruby'), ('Flutter', 'flutter')], max_length=50, verbose_name='Tanlagan kursi'),
        ),
    ]
